import os, sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from typing import List, TypedDict
from config import HTML_DIR
from object_types import PLAYER_DATA
from parser import process_file

class TEST_FILE(TypedDict):
    file_path: str
    expected_values: PLAYER_DATA

def test_extractor(f: TEST_FILE):
    extracted = process_file('', f['file_path'])

    assert extracted is not None, '❌ failed to extract data'

    for key, value in extracted.items():
        if key in ['file_path', 'download_url']:
            continue
        assert value == f['expected_values'][key], f'❌ {key} value not good'

    print(f'✔ {f['file_path']} passed')

test_files: List[TEST_FILE] = [{
        'file_path': os.path.join(HTML_DIR, 'addisca01.html'),
        'expected_values': {
            'player_name': 'Calen Addison',
            'position': 'D',
            'dob': 'April 11, 2000',
            'draft_team': 'Pittsburgh',
            'hand': 'Right',
            'height': 180,
            'weight': 78,
            'games_played': 152,
            'goals': 6,
            'assists': 44,
            'points': 50,
            'plus_minus': -59,
            'point_shares': 4.2,
            'penalty_minutes': 96,
            'shots_on_goal': 191,
            'game_winning_goals': 1,
            'wins': None,
            'losses': None,
            'download_url': '', # nechcelo sa mi vyrabat novy typ
            'file_path': '', # nechcelo sa mi vyrabat novy typ
            'gaa': None,
            'minutes': None,
            'save_percentage': None,
            'shootouts': None,
            'ties_ot_losses': None
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'agostke01.html'), 
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Kenny Agostino',
            'dob': 'April 30, 1992',
            'position': 'LW',
            'draft_team': 'Pittsburgh',
            'hand': 'Left',
            'height': 183,
            'weight': 90,
            'games_played': 86,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 8,
            'assists': 22,
            'points': 30,
            'plus_minus': -8,
            'point_shares': 1.9,
            'penalty_minutes': 40,
            'shots_on_goal': 122,
            'game_winning_goals': 0
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'altma01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Mark Alt',
            'dob': 'October 18, 1991',
            'position': 'D',
            'draft_team': 'Carolina',
            'hand': 'Right',
            'height': 193,
            'weight': 90,
            'games_played': 20,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 0,
            'assists': 0,
            'points': 0,
            'plus_minus': -2,
            'point_shares': 0.0,
            'penalty_minutes': 4,
            'shots_on_goal': 16,
            'game_winning_goals': 0
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'amadimi01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Michael Amadio',
            'dob': 'May 13, 1996',
            'position': 'C',
            'draft_team': 'Los Angeles',
            'hand': 'Right',
            'height': 185,
            'weight': 93,
            'games_played': 442,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 68,
            'assists': 71,
            'points': 139,
            'plus_minus': 2,
            'point_shares': 11.9,
            'penalty_minutes': 89,
            'shots_on_goal': 553,
            'game_winning_goals': 8
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'klingjo01.html'), 
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'John Klingberg',
            'dob': 'August 14, 1992',
            'position': 'D',
            'draft_team': 'Dallas',
            'hand': 'Right',
            'height': 188,
            'weight': 83,
            'games_played': 645,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 82,
            'assists': 335,
            'points': 417,
            'plus_minus': -41,
            'point_shares': 63.7,
            'penalty_minutes': 263,
            'shots_on_goal': 1265,
            'game_winning_goals': 24
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'klinkro01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Rob Klinkhammer',
            'dob': 'August 12, 1986',
            'position': 'LW',
            'draft_team': None,
            'hand': 'Left',
            'height': 190,
            'weight': 97,
            'games_played': 193,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 22,
            'assists': 21,
            'points': 43,
            'plus_minus': 4,
            'point_shares': 3.8,
            'penalty_minutes': 64,
            'shots_on_goal': 238,
            'game_winning_goals': 2
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'knublmi01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Michael Rudolf Knuble',
            'dob': 'July 4, 1972',
            'position': 'RW',
            'draft_team': 'Detroit',
            'hand': 'Right',
            'height': 190,
            'weight': 103,
            'games_played': 1068,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 278,
            'assists': 270,
            'points': 548,
            'plus_minus': 76,
            'point_shares': 60.4,
            'penalty_minutes': 641,
            'shots_on_goal': 2004,
            'game_winning_goals': 36
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'koekksl01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Slater Koekkoek',
            'dob': 'February 18, 1994',
            'position': 'D',
            'draft_team': 'Tampa Bay',
            'hand': 'Left',
            'height': 188,
            'weight': 87,
            'games_played': 186,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 8,
            'assists': 26,
            'points': 34,
            'plus_minus': 1,
            'point_shares': 5.9,
            'penalty_minutes': 104,
            'shots_on_goal': 198,
            'game_winning_goals': 2
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'koivumi01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Mikko Koivu',
            'dob': 'March 12, 1983',
            'position': 'C',
            'draft_team': 'Minnesota',
            'hand': 'Left',
            'height': 190,
            'weight': 96,
            'games_played': 1035,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 206,
            'assists': 505,
            'points': 711,
            'plus_minus': 68,
            'point_shares': 70.3,
            'penalty_minutes': 594,
            'shots_on_goal': 2273,
            'game_winning_goals': 33
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'koivusa01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Saku Koivu',
            'dob': 'November 23, 1974',
            'position': 'C',
            'draft_team': 'Montreal',
            'hand': 'Left',
            'height': 178,
            'weight': 82,
            'games_played': 1124,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 255,
            'assists': 577,
            'points': 832,
            'plus_minus': 10,
            'point_shares': 79.6,
            'penalty_minutes': 809,
            'shots_on_goal': 2024,
            'game_winning_goals': 46
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'koleske01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Keegan Kolesar',
            'dob': 'April 8, 1997',
            'position': 'RW',
            'draft_team': 'Columbus',
            'hand': 'Right',
            'height': 188,
            'weight': 97,
            'games_played': 363,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 38,
            'assists': 66,
            'points': 104,
            'plus_minus': -9,
            'point_shares': 6.3,
            'penalty_minutes': 270,
            'shots_on_goal': 369,
            'game_winning_goals': 5
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'komarle01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Leo Komarov',
            'dob': 'January 23, 1987',
            'position': 'C',
            'draft_team': 'Toronto',
            'hand': 'Left',
            'height': 180,
            'weight': 92,
            'games_played': 491,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 63,
            'assists': 107,
            'points': 170,
            'plus_minus': 20,
            'point_shares': 13.5,
            'penalty_minutes': 207,
            'shots_on_goal': 644,
            'game_winning_goals': 10
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'kopitan01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'AnÅ',
            'dob': 'August 24, 1987',
            'position': 'C',
            'draft_team': 'Los Angeles',
            'hand': 'Left',
            'height': 190,
            'weight': 102,
            'games_played': 1458,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 440,
            'assists': 842,
            'points': 1282,
            'plus_minus': 110,
            'point_shares': 138.9,
            'penalty_minutes': 348,
            'shots_on_goal': 3334,
            'game_winning_goals': 78
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'korpila01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Lauri Korpikoski',
            'dob': 'July 28, 1986',
            'position': 'LW',
            'draft_team': 'NY Rangers',
            'hand': 'Left',
            'height': 185,
            'weight': 87,
            'games_played': 609,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 86,
            'assists': 115,
            'points': 201,
            'plus_minus': -49,
            'point_shares': 14.8,
            'penalty_minutes': 132,
            'shots_on_goal': 850,
            'game_winning_goals': 12
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'lainepa01.html'),
        'expected_values': {  
            'file_path': '',
            'download_url': '',
            'player_name': 'Patrik Laine',
            'dob': 'April 19, 1998',
            'position': 'RW',
            'draft_team': 'Winnipeg',
            'hand': 'Right',
            'height': 193,
            'weight': 94,
            'games_played': 537,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 224,
            'assists': 198,
            'points': 422,
            'plus_minus': -75,
            'point_shares': 46.7,
            'penalty_minutes': 201,
            'shots_on_goal': 1512,
            'game_winning_goals': 31
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'malkiev01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Evgeni Vladimirovich Malkin',
            'dob': 'July 31, 1986',
            'position': 'C',
            'draft_team': 'Pittsburgh',
            'hand': 'Left',
            'height': 196,
            'weight': 96,
            'games_played': 1219,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 516,
            'assists': 839,
            'points': 1355,
            'plus_minus': 29,
            'point_shares': 156.1,
            'penalty_minutes': 1202,
            'shots_on_goal': 3822,
            'game_winning_goals': 86
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'ovechal01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Alexander Mikhaylovich Ovechkin',
            'dob': 'September 17, 1985',
            'position': 'LW',
            'draft_team': 'Washington',
            'hand': 'Right',
            'height': 190,
            'weight': 107,
            'games_played': 1496,
            'wins': None,
            'losses': None,
            'ties_ot_losses': None,
            'minutes': None,
            'gaa': None,
            'save_percentage': None,
            'shootouts': None,
            'goals': 898,
            'assists': 729,
            'points': 1627,
            'plus_minus': 65,
            'point_shares': 214.3,
            'penalty_minutes': 833,
            'shots_on_goal': 6878,
            'game_winning_goals': 136
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'roypa01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Patrick Roy',
            'dob': 'October 5, 1965',
            'position': 'G',
            'draft_team': 'Montreal',
            'hand': 'Left',
            'height': 188,
            'weight': 83,
            'games_played': 1029,
            'wins': 551,
            'losses': 100,
            'ties_ot_losses': 131,
            'minutes': 60214,
            'gaa': 2.54,
            'save_percentage': 0.91,
            'shootouts': 66,
            'goals': None,
            'assists': None,
            'points': None,
            'plus_minus': None,
            'point_shares': 198.3,
            'penalty_minutes': None,
            'shots_on_goal': None,
            'game_winning_goals': None
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'lundqhe01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Henrik Lundqvist',
            'dob': 'March 2, 1982',
            'position': 'G',
            'draft_team': 'NY Rangers',
            'hand': 'Left',
            'height': 185,
            'weight': 82,
            'games_played': 887,
            'wins': 459,
            'losses': 310,
            'ties_ot_losses': 96,
            'minutes': 51818,
            'gaa': 2.43,
            'save_percentage': 0.918,
            'shootouts': 64,
            'goals': None,
            'assists': None,
            'points': None,
            'plus_minus': None,
            'point_shares': 173.3,
            'penalty_minutes': None,
            'shots_on_goal': None,
            'game_winning_goals': None
        }
    }, {
        'file_path': os.path.join(HTML_DIR, 'brodema01.html'),
        'expected_values': {   
            'file_path': '',
            'download_url': '',
            'player_name': 'Martin Pierre Brodeur',
            'dob': 'May 6, 1972',
            'position': 'G',
            'draft_team': 'New Jersey',
            'hand': 'Left',
            'height': 188,
            'weight': 99,
            'games_played': 1266,
            'wins': 691,
            'losses': 100,
            'ties_ot_losses': 154,
            'minutes': 74439,
            'gaa': 2.24,
            'save_percentage': 0.912,
            'shootouts': 125,
            'goals': None,
            'assists': None,
            'points': None,
            'plus_minus': None,
            'point_shares': 207.0,
            'penalty_minutes': None,
            'shots_on_goal': None,
            'game_winning_goals': None
        }
    }
]


if __name__ == '__main__':
    for file in test_files:
        test_extractor(file)